// Every number shown in the dashboard comes from this file, which is
// generated by scripts/export_dashboard_data.py from the trained
// checkpoints, the fitted demand model, and the training/eval logs.
import raw from "../data/dashboard_data.json";

export const DATA = raw;
export const META = raw.meta;
export const ALGOS = META.algorithms; // [{ key, label, color, action_space, policy }]
export const BASELINES = META.baselines; // [{ key, label, color }]
export const ALL_POLICIES = [...BASELINES, ...ALGOS];
export const SEEDS = META.seeds.map(String);
export const SEED_OPTIONS = [...SEEDS, "mean"];
export const PRODUCTS = raw.products;
export const TRAINING = raw.training;
export const SUMMARY = raw.summary;
export const HISTORICAL = { key: "historical", label: "Historical (seller's price)", color: META.historical_color };

export const sum = (a) => a.reduce((x, y) => x + y, 0);
export const mean = (a) => (a.length ? sum(a) / a.length : 0);

export function policyMeta(key) {
  return ALL_POLICIES.find((p) => p.key === key) || HISTORICAL;
}

/** Per-month trajectory for one policy on one product, for a seed or the cross-seed mean. */
export function agentSeries(product, key, seed) {
  const bySeed = product.agents[key];
  if (seed !== "mean") return bySeed[seed] || bySeed[Object.keys(bySeed)[0]];
  const seeds = Object.keys(bySeed);
  const n = product.months.length;
  const avg = (field) => Array.from({ length: n }, (_, i) => seeds.reduce((a, s) => a + bySeed[s][field][i], 0) / seeds.length);
  return {
    price: avg("price"),
    qty: avg("qty"),
    revenue: avg("revenue"),
    rcr: avg("rcr"),
    drcr: avg("drcr"),
    clipped: Array.from({ length: n }, (_, i) => seeds.some((s) => bySeed[s].clipped[i])),
  };
}

export function cumulative(arr) {
  const out = [];
  let acc = 0;
  for (const v of arr) {
    acc += v;
    out.push(acc);
  }
  return out;
}

/** Cumulative-to-month summary for one product: revenue, uplift vs. the historical price path, mean DRCR. */
export function productSummary(product, seed, upTo = null) {
  const end = upTo == null ? product.months.length : upTo + 1;
  const histRev = sum(product.historical.revenue_model.slice(0, end));
  const policies = {};
  for (const p of ALL_POLICIES) {
    const s = agentSeries(product, p.key, seed);
    const rev = sum(s.revenue.slice(0, end));
    policies[p.key] = {
      rev,
      uplift: histRev ? ((rev - histRev) / histRev) * 100 : 0,
      drcr: mean(s.drcr.slice(0, end)),
      clippedMonths: s.clipped.slice(0, end).filter(Boolean).length,
    };
  }
  return { id: product.id, category: product.category, histRev, policies };
}

/** Linear interpolation of a price-grid field at an arbitrary price. */
export function interpGrid(grid, field, price) {
  const xs = grid.prices;
  const ys = grid[field];
  if (price <= xs[0]) return ys[0];
  if (price >= xs[xs.length - 1]) return ys[ys.length - 1];
  let i = 1;
  while (i < xs.length && xs[i] < price) i++;
  const t = (price - xs[i - 1]) / (xs[i] - xs[i - 1]);
  return ys[i - 1] + t * (ys[i] - ys[i - 1]);
}
